/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_MediaRecorder */

#ifndef _Included_com_example_MediaRecorder
#define _Included_com_example_MediaRecorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_MediaRecorder
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_MediaRecorder_native_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_example_MediaRecorder
 * Method:    native_set
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_MediaRecorder_native_1set
  (JNIEnv *, jclass);

/*
 * Class:     com_example_MediaRecorder
 * Method:    wmp_saet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_MediaRecorder_wmp_1saet
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
